import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'appName': "Wird",
      'home': 'Home',
      'prayer': 'Prayer Times',
      'quran': 'Quran',
      'adhkar': 'Adhkar',
      'hijri': 'Hijri Calendar',
      'qibla': 'Qibla',
      'mosque': 'Mosque Finder',
      'tasbeeh': 'Tasbeeh',
      'settings': 'Settings',
      'nextPrayer': 'Next Prayer',
      'readQuran': 'Read Quran',
      'qiblaCompass': 'Qibla',
      'mosqueFinder': 'Mosque Finder',
      'tasbeehCounter': 'Tasbeeh',
      'permissions': 'Permissions',
      'locationRequired': 'Location access is needed for prayer times and mosque finder.',
      'notificationsRequired': 'Notifications are needed for adhan reminders.',
      'grantPermissions': 'Grant Permissions',
      'fajr': 'Fajr',
      'sunrise': 'Sunrise',
      'dhuhr': 'Dhuhr',
      'asr': 'Asr',
      'maghrib': 'Maghrib',
      'isha': 'Isha',
      'jumuah': "Jumu'ah",
      'morning': 'Morning',
      'evening': 'Evening',
      'sleep': 'Sleep',
      'afterPrayer': 'After Prayer',
      'wakeUp': 'Wake Up',
      'completionDua': 'Completion Dua',
      'appearance': 'Appearance',
      'language': 'Language',
      'system': 'System',
      'light': 'Light',
      'dark': 'Dark',
      'english': 'English',
      'arabic': 'Arabic',
      'about': 'About',
      'today': 'Today',
      'tomorrow': 'Tomorrow',
      'remaining': 'remaining',
      'upcomingPrayers': 'Upcoming Prayers',
      'viewMore': 'View More',
      'seeAll': 'See all',
      'quickAccess': 'Quick Access',
      'lastReadPage': 'Last read: Page %s of 604',
      'next': 'Next',
      'quranCompletionPlan': 'Quran Completion Plan',
      'duaAdhkar': 'Dua & Adhkar',
      // Greetings
      'goodMorning': 'Good Morning',
      'goodAfternoon': 'Good Afternoon',
      'goodEvening': 'Good Evening',
      // Quran
      'continueReading': 'Continue Reading',
      'surah': 'Surah',
      'surahs': 'Surahs',
      'juz': 'Juz',
      'verses': 'verses',
      'pages': 'Pages',
      'searchJuz': 'Search juz…',
      'noSurahsFound': 'No surahs found',
      'makki': 'Makki',
      'madani': 'Madani',
      'searchSurahs': 'Search surahs...',
      'searchReciters': 'Search reciter...',
      'reciter': 'Reciter',
      'quranReader': 'Quran Reader',
      'chooseReciter': 'Choose Reciter',
      'recitersCount': '%s reciters',
      'noRecitersFound': 'No reciters found',
      'reciterChangedSuccess': 'Reciter changed successfully',
      'changeReciter': 'Change',
      'popularReciters': 'Popular Reciters',
      'allReciters': 'All Reciters',
      'playSurah': 'Play Surah',
      'playAyah': 'Play Ayah',
      'viewTafsir': 'View Tafsir',
      'translate': 'Translate',
      'bookmark': 'Bookmark',
      'share': 'Share',
      'tafsir': 'Tafsir',
      'comingSoon': 'Coming Soon',
      'bookmarkAdded': 'Bookmark Added',
      'noTafsirAvailable': 'No tafsir available',
      'audioPlayError': 'Unable to play audio. Check your connection.',
      'prev': 'Prev',
      'ayahOf': 'Ayah %s of %s',
      'pageOf': 'Page %s of 604',
      // Qibla
      'qiblaDirection': 'Qibla Direction',
      'heading': 'Heading',
      'facingQibla': 'Facing the Qibla',
      'turnRight': 'Turn %s° right',
      'turnLeft': 'Turn %s° left',
      'degrees': '°',
      'masjidHaram': 'Masjid Al-Haram',
      'meccaSaudiArabia': 'Mecca, Saudi Arabia',
      'masjidHaramMecca': 'Masjid Al-Haram · Mecca, Saudi Arabia',
      // Settings
      'general': 'General',
      'theme': 'Theme',
      'chooseTheme': 'Choose Theme',
      'chooseLanguage': 'Choose Language',
      'customizeExperience': 'Customize your experience',
      'systemDefault': 'System default',
      'followDeviceSetting': 'Follow device setting',
      'alwaysLightTheme': 'Always light theme',
      'alwaysDarkTheme': 'Always dark theme',
      'appNameLabel': 'App Name',
      'appVersion': 'Version',
      'allGranted': 'All granted',
      'somePending': 'Some pending',
      // Adhkar
      'adhkarDuas': 'Adhkar & Duas',
      'adhkarVerse': '"And remember Allah much that you may succeed." — 62:10',
      'goingOut': 'Leaving Home',
      'enteringHome': 'Entering Home',
      'forgiveness': 'Forgiveness',
      'tasbih': 'Tasbih',
      'nextDhikr': 'Next Dhikr',
      'reset': 'Reset',
      // Notifications
      'notifications': 'Notifications',
      'prayerNotifications': 'Prayer Notifications',
      'adhkarNotifications': 'Adhkar Notifications',
      'morningAdhkarReminder': 'Morning Adhkar Reminder',
      'eveningAdhkarReminder': 'Evening Adhkar Reminder',
      'sleepAdhkarReminder': 'Sleep Adhkar Reminder',
      'notifTitleMorning': 'Morning Adhkar',
      'notifTitleEvening': 'Evening Adhkar',
      'notifTitleSleep': 'Sleep Adhkar',
      'notifBodyMorning': 'Start your day with the remembrance of Allah',
      'notifBodyEvening': 'End your day with the remembrance of Allah',
      'notifBodySleep': 'Do not forget the sleep adhkar before you sleep',
      'sleepTime': 'Sleep Time',
      'enableReminder': 'Enable Reminder',
      'minutesBefore': '10 minutes before',
      'exactAlarmRequired': 'Exact Alarm Required',
      'exactAlarmMessage': 'For accurate prayer time notifications, please allow exact alarms in system settings.',
      'openSettings': 'Open Settings',
      // Mood-Based Adhkar
      'howAreYouFeeling': 'How are you feeling today?',
      'selectYourMood': 'Select your mood',
      'moodAnxious': 'Anxious',
      'moodGrateful': 'Grateful',
      'moodSad': 'Sad',
      'moodMotivated': 'Motivated',
      'recommendedForYou': 'Recommended for you',
      'duas': 'Duas',
      'ayahs': 'Ayahs',
      'dhikr': 'Dhikr',
      'moodBasedRecommendations': 'Mood-Based Recommendations',
    },
    'ar': {
      'appName': 'ورد',
      'home': 'الرئيسية',
      'prayer': 'أوقات الصلاة',
      'quran': 'القرآن',
      'adhkar': 'الأذكار',
      'hijri': 'التقويم الهجري',
      'qibla': 'القبلة',
      'mosque': 'البحث عن المساجد',
      'tasbeeh': 'التسبيح',
      'settings': 'الإعدادات',
      'nextPrayer': 'الصلاة القادمة',
      'readQuran': 'اقرأ القرآن',
      'qiblaCompass': 'القبلة',
      'mosqueFinder': 'البحث عن المساجد',
      'tasbeehCounter': 'التسبيح',
      'permissions': 'الأذونات',
      'locationRequired': 'نحتاج موقعك لأوقات الصلاة والبحث عن المساجد.',
      'notificationsRequired': 'الإشعارات مطلوبة لتذكير الأذان.',
      'grantPermissions': 'منح الأذونات',
      'fajr': 'الفجر',
      'sunrise': 'الشروق',
      'dhuhr': 'الظهر',
      'asr': 'العصر',
      'maghrib': 'المغرب',
      'isha': 'العشاء',
      'jumuah': 'الجمعة',
      'morning': 'أذكار الصباح',
      'evening': 'أذكار المساء',
      'sleep': 'أذكار النوم',
      'afterPrayer': 'أذكار بعد الصلاة',
      'wakeUp': 'أذكار الاستيقاظ',
      'completionDua': 'دعاء الختم',
      'appearance': 'المظهر',
      'language': 'اللغة',
      'system': 'النظام',
      'light': 'فاتح',
      'dark': 'داكن',
      'english': 'الإنجليزية',
      'arabic': 'العربية',
      'about': 'حول',
      'today': 'اليوم',
      'tomorrow': 'غداً',
      'remaining': 'متبقي',
      'upcomingPrayers': 'الصلوات القادمة',
      'viewMore': 'عرض المزيد',
      'seeAll': 'عرض الكل',
      'quickAccess': 'وصول سريع',
      'lastReadPage': 'آخر قراءة: صفحة %s من 604',
      'next': 'التالي',
      'quranCompletionPlan': 'خطة إتمام القرآن',
      'duaAdhkar': 'الدعاء والأذكار',
      // Greetings
      'goodMorning': 'صباح الخير',
      'goodAfternoon': 'مساء الخير',
      'goodEvening': 'مساء الخير',
      // Quran
      'continueReading': 'متابعة القراءة',
      'surah': 'سورة',
      'surahs': 'سور',
      'juz': 'جزء',
      'verses': 'آيات',
      'pages': 'صفحات',
      'searchJuz': 'البحث عن الجزء...',
      'noSurahsFound': 'لم يتم العثور على سور',
      'makki': 'مكية',
      'madani': 'مدنية',
      'searchSurahs': 'البحث عن السور...',
      'searchReciters': 'البحث عن القارئ...',
      'reciter': 'القارئ',
      'quranReader': 'قارئ القرآن',
      'chooseReciter': 'اختر القارئ',
      'recitersCount': '%s قارئ',
      'noRecitersFound': 'لم يتم العثور على قارئ',
      'reciterChangedSuccess': 'تم تغيير القارئ بنجاح',
      'changeReciter': 'تغيير',
      'popularReciters': 'القراء المشهورون',
      'allReciters': 'جميع القراء',
      'playSurah': 'تشغيل السورة',
      'playAyah': 'تشغيل الآية',
      'viewTafsir': 'عرض التفسير',
      'translate': 'ترجمة',
      'bookmark': 'حفظ في المفضلة',
      'share': 'مشاركة',
      'tafsir': 'التفسير',
      'comingSoon': 'قريباً',
      'bookmarkAdded': 'تمت الإضافة للمفضلة',
      'noTafsirAvailable': 'لا يوجد تفسير',
      'audioPlayError': 'تعذر تشغيل الصوت. تحقق من اتصالك.',
      'prev': 'السابق',
      'ayahOf': 'آية %s من %s',
      'pageOf': 'صفحة %s من 604',
      // Qibla
      'qiblaDirection': 'اتجاه القبلة',
      'heading': 'الاتجاه',
      'facingQibla': 'متجه نحو القبلة',
      'turnRight': 'أدر %s° لليمين',
      'turnLeft': 'أدر %s° لليسار',
      'degrees': '°',
      'masjidHaram': 'المسجد الحرام',
      'meccaSaudiArabia': 'مكة المكرمة، المملكة العربية السعودية',
      'masjidHaramMecca': 'المسجد الحرام · مكة المكرمة',
      // Settings
      'general': 'عام',
      'theme': 'المظهر',
      'chooseTheme': 'اختر المظهر',
      'chooseLanguage': 'اختر اللغة',
      'customizeExperience': 'خصص تجربتك',
      'systemDefault': 'افتراضي النظام',
      'followDeviceSetting': 'اتباع إعداد الجهاز',
      'alwaysLightTheme': 'مظهر فاتح دائماً',
      'alwaysDarkTheme': 'مظهر داكن دائماً',
      'appNameLabel': 'اسم التطبيق',
      'appVersion': 'الإصدار',
      'allGranted': 'الكل ممنوح',
      'somePending': 'بعضها معلق',
      // Adhkar
      'adhkarDuas': 'الأذكار والدعاء',
      'adhkarVerse': '"واذكروا الله كثيراً لعلكم تفلحون" — 62:10',
      'goingOut': 'أذكار الخروج',
      'enteringHome': 'أذكار الدخول',
      'forgiveness': 'الاستغفار',
      'tasbih': 'التسبيح',
      'nextDhikr': 'الذكر التالي',
      'reset': 'إعادة',
      // Notifications
      'notifications': 'الإشعارات',
      'prayerNotifications': 'إشعارات الصلاة',
      'adhkarNotifications': 'إشعارات الأذكار',
      'morningAdhkarReminder': 'تذكير أذكار الصباح',
      'eveningAdhkarReminder': 'تذكير أذكار المساء',
      'sleepAdhkarReminder': 'تذكير أذكار النوم',
      'notifTitleMorning': 'أذكار الصباح',
      'notifTitleEvening': 'أذكار المساء',
      'notifTitleSleep': 'أذكار النوم',
      'notifBodyMorning': 'ابدأ يومك بذكر الله',
      'notifBodyEvening': 'اختم يومك بذكر الله',
      'notifBodySleep': 'لا تنس أذكار النوم قبل أن تغفو',
      'sleepTime': 'وقت النوم',
      'enableReminder': 'تفعيل التذكير',
      'minutesBefore': 'قبل 10 دقائق',
      'exactAlarmRequired': 'مطلوب تنبيه دقيق',
      'exactAlarmMessage': 'للحصول على إشعارات دقيقة لأوقات الصلاة، يرجى السماح بالتنبيهات الدقيقة في إعدادات النظام.',
      'openSettings': 'فتح الإعدادات',
      // Mood-Based Adhkar
      'howAreYouFeeling': 'كيف تشعر اليوم؟',
      'selectYourMood': 'اختر مزاجك',
      'moodAnxious': 'قلق',
      'moodGrateful': 'ممتن',
      'moodSad': 'حزين',
      'moodMotivated': 'متحمس',
      'recommendedForYou': 'موصى به لك',
      'duas': 'الأدعية',
      'ayahs': 'الآيات',
      'dhikr': 'الذكر',
      'moodBasedRecommendations': 'توصيات مبنية على المزاج',
    },
  };

  String translate(String key, [List<Object> args = const []]) {
    var s = _localizedValues[locale.languageCode]?[key] ?? key;
    for (final arg in args) {
      s = s.replaceFirst('%s', arg.toString());
    }
    return s;
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'ar'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
